[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm ci --prefix client",
  "npm ci --prefix server",
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "cd server && npx prisma generate && npm run build",
]

[start]
cmd = "cd server && npx prisma migrate deploy && npm start"
